# Generated by Django 2.1.15 on 2020-11-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_blogsreal_8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogsreal_8',
            new_name='captcha_id',
        ),
    ]
